<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\KickSneak.BackgroundServices\KickSneak.BackgroundServices.csproj" />
    <ProjectReference Include="..\KickSneak.Application\KickSneak.Application.csproj" />
    <ProjectReference Include="..\KickSneak.Persistence\KickSneak.Persistence.csproj" />
    <ProjectReference Include="..\KickSneak.Infrastructure\KickSneak.Infrastructure.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Update="FirebaseConfig\firebase-config.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
